# Site settings
title: Morning Hypertext
description: by Ryan Johnson
url: "http://tenthirtyam.org"
baseurl: "http://tenthirtyam.org/"
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'tenthirtyam'

author:
  name: Ryan Johnson
  twitter_username: tenthirtyam
  github_username: tenthirtyam
  linkedin_username: tenthirtyam

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
timezone: "America/NewYork"
destination: _site
paginate: 1
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
